config/routes.rb
Statik::Application.routes.draw do
  root              to: "static_pages#home"
  devise_for        :users
  resources         :users, :only => [:show, :index]
  devise_for        :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  match 'register', to: 'devise/registrations#new', as: :new_user_registration
  
  authenticated :user do
    root            to: 'static_pages#home'
  end

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

  
  match '*path', :to => 'error#routing_error'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role :admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_presence_of   :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def routing_error
    render file: "#{Rails.root}/public/404.html", status: 404, layout: false
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "WordIntel"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">BaseTop - @jsinghfoss</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BaseTop", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>

          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
              	<li><%= link_to('Profile', edit_user_registration_path) %></li>
              	<% if current_user.has_role? :admin %>
      			<li><%= link_to('Admin', users_path) %></li>
    			<% end %>
                <li class="divider"></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %> </li>
              </ul>
            </li>
          <% else %>
    		<li><%= link_to('Login', new_user_session_path) %></li>
		  <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
   	<div class="container">
      	<% flash.each do |key, value| %>
        	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%> 
<h1>About Us</h1>
<p>
	Coming soon...
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%> 
<h1>Contact</h1>
<p>
	Coming soon...
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %> 
<h1>Help</h1>
<p>
	Coming soon...
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>BaseTop by @jsinghfoss</h1>
  <p class="lead">Rails 3.2.6, Devise, Twitter Bootstrap, SASS</p>
  <% if !user_signed_in? %>
  	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  <% end %> 
</div>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>